# Generated by Django 4.0.3 on 2022-12-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='counter',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='counter',
            name='unit',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
