# Generated by Django 4.1.10 on 2023-07-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("counters", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reading",
            options={"ordering": ("-date",)},
        ),
        migrations.AddField(
            model_name="counter",
            name="consumable",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="counter",
            name="fixed_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="counter",
            name="price_per_unit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="counter",
            name="unit",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="reading",
            name="value",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
