# Generated by Django 4.1.10 on 2023-07-16 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("counters", "0002_alter_reading_options_counter_consumable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="counter",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
