# Generated by Django 4.0.3 on 2022-12-10 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0004_alter_counter_price_per_unit_alter_reading_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ('-date',)},
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_units', models.DecimalField(decimal_places=2, max_digits=10)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='counters.counter')),
            ],
        ),
    ]
