# Generated by Django 4.0.3 on 2022-12-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0005_alter_reading_options_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='usage_in_units',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Usage',
        ),
    ]
