# Generated by Django 4.0.3 on 2022-12-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0006_reading_usage_in_units_delete_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='consumable',
            field=models.BooleanField(default=True),
        ),
    ]
