# Generated by Django 4.0 on 2023-07-29 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("counters", "0007_remove_counter_fixed_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="reading",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="counters.reading",
            ),
        ),
    ]
