# Generated by Django 4.0 on 2023-07-30 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("counters", "0012_reading_usage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="usage",
        ),
        migrations.RemoveField(
            model_name="reading",
            name="usage",
        ),
    ]
