# Generated by Django 4.1.10 on 2024-01-15 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0014_reading_usage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
