# Generated by Django 4.1.10 on 2024-01-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0015_remove_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='usage',
        ),
    ]
