# Generated by Django 4.0.1 on 2022-04-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('isbn', models.CharField(max_length=50)),
                ('page_count', models.IntegerField()),
                ('imageLinks', models.URLField()),
                ('language', models.CharField(max_length=2)),
                ('author', models.ManyToManyField(related_name='authored', to='books.Author')),
            ],
        ),
    ]
