# Generated by Django 4.0.3 on 2023-01-16 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OH', 'ON HOLD'), ('NS', 'NOT STARTED'), ('IP', 'IN PROGRESS'), ('C', 'COMPLETE')], default='NS', max_length=10)),
                ('priority', models.CharField(choices=[('L', 'LOW'), ('H', 'HIGH')], default='L', max_length=10)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones_assignments', to='project_manager.member')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones_authored', to='project_manager.member')),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('login', models.CharField(max_length=64, null=True)),
                ('password', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('L', 'LOW'), ('H', 'HIGH')], default='L', max_length=10)),
                ('status', models.CharField(choices=[('OH', 'ON HOLD'), ('NS', 'NOT STARTED'), ('IP', 'IN PROGRESS'), ('C', 'COMPLETE')], default='NS', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_authored', to='project_manager.member')),
                ('members', models.ManyToManyField(blank=True, related_name='project_members', to='project_manager.member')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project_manager.organization')),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('complete', models.BooleanField(default=False)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project_manager.milestone')),
            ],
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_milestones', to='project_manager.project'),
        ),
        migrations.AddField(
            model_name='member',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='project_manager.organization'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DayTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('OH', 'ON HOLD'), ('NS', 'NOT STARTED'), ('IP', 'IN PROGRESS'), ('C', 'COMPLETE')], default='NS', max_length=10)),
                ('priority', models.CharField(choices=[('L', 'LOW'), ('H', 'HIGH')], default='L', max_length=10)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='project_manager.daytask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_tasks', to='project_manager.member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
